main: main.java.codes.anhgelus.architectsLand.ArchitectsLand
name: ArchitectsLand
version: 0.5.7-beta.7
author: Anhgelus
depend: [DiscordSRV]
commands:
  f:
    description: Faction base command
    usage: Command error
  broadcast:
    description: Broadcast to every players
    usage: Command error
    aliases:
      - bc
  announcement:
    description: Send an announce to every players
    usage: Command error
    aliases:
      - ann