main: main.java.codes.anhgelus.architectsLand.ArchitectsLand
name: ArchitectsLand
version: 0.2.4-dev.5
author: Anhgelus
commands:
  f:
    description: Faction base command
    usage: Command error
  broadcast:
    description: Broadcast to every player
    usage: Command error
    aliases:
      - bc
