main: main.java.codes.anhgelus.architectsLand.ArchitectsLand
name: ArchitectsLand
version: 0.8.2-beta.4
author: Anhgelus
depend: [DiscordSRV]
commands:
  f:
    description: Faction base command (use /f for more informations)
    usage: Command error
  broadcast:
    description: Broadcast to every players
    usage: Command error
    aliases:
      - bc
  announcement:
    description: Send an announce to every players
    usage: Command error
    aliases:
      - ann
  home:
    description: Teleport to the player's home
    usage: Command error
  sethome:
    description: Set the player's home
    usage: Command error
  base:
    description: Base base command (use /b or /base for more informations)
    usage: Command error
    aliases:
      - b